### ISSUE TITLE
今年的还可以正常使用吗

### ISSUE THREAD

**Issue by huoshenw** [rootklt/liangongbao_wechat#2]
今年的还可以正常使用吗

**Comment by huoshenw** [comment]
F:\liangongbao_wechat-main>py main.py
2024-06-01 09:04:14.357 | INFO     | Process_wx:activity_competition:92 - {"result":{"msg":"成功"},"data":{"isRegist":true,"userCode":1002715040}}
2024-06-01 09:04:14.666 | INFO     | Process_wx:start_competition:137 - {'result': {'msg': '成功'}, 'data': {'ques': {'quesNo': 1, 'options': ['3', '5', '10'], 'quesTypeStr': '单选题', 'quesId': 'PBBLZLNM7hmkPiAU', 'content': '谎报火警是违 法行为，最高可以处（ ）日拘留。', 'quesType': 1}, 'remainder': 150}}
2024-06-01 09:04:14.668 | INFO     | Process_wx:answer_question:202 - 开始答题：1717203854.6689672
2024-06-01 09:04:14.669 | INFO     | Process_wx:search_answer:178 - [-]题库无该题:单选题，默认选择答案：3
2024-06-01 09:04:14.797 | INFO     | Process_wx:answer_question:209 - {"timestamp":"2024-06-01T01:02:09.170+00:00","status":400,"error":"Bad Request","path":"/aqy/ques/answerQues"}
Traceback (most recent call last):
  File "F:\liangongbao_wechat-main\Process_wx.py", line 154, in search_answer
    assert data and isinstance(data, dict)
AssertionError
2024-06-01 09:04:20.813 | ERROR    | Process_wx:search_answer:181 -
2024-06-01 09:04:20.878 | INFO     | Process_wx:answer_question:209 - {"timestamp":"2024-06-01T01:02:15.252+00:00","status":400,"error":"Bad Request","path":"/aqy/ques/answerQues"}
Traceback (most recent call last):
  File "F:\liangongbao_wechat-main\Process_wx.py", line 154, in search_answer
    assert data and isinstance(data, dict)
AssertionError
成功后报错
